### Login
POST http://localhost:3000/auth/sign-in
content-type: application/json

{
  "email": "budiharta_21@live.com",
  "password": "superSecretPass"
}

### Request refresh token
POST http://localhost:3000/auth/refresh-token
content-type: application/json

{
  "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJCdWRpaGFydGEiLCJlbWFpbCI6ImJ1ZGloYXJ0YV8yMUBsaXZlLmNvbSIsImlhdCI6MTcwNTc1OTAxMywiZXhwIjoxNzA4MzUxMDEzfQ.WQyHGOy_u1zBKD29Rti1yiI5unpDWWm1Z1fstG9kjqg"
}


### Get user
GET http://localhost:3000/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJCdWRpaGFydGEiLCJlbWFpbCI6ImJ1ZGloYXJ0YV8yMUBsaXZlLmNvbSIsImlhdCI6MTcwNTc1OTE3NCwiZXhwIjoxNzA1NzU5MjM0fQ.HA_KW6rrixEXNoCsu1Wec5eiKtoY-Uv_XtQEgRG1FCY
