### Login
POST http://localhost:3000/auth/sign-in
content-type: application/json

{
  "email": "budiharta_21@live.com",
  "password": "superSecretPass"
}

### Request refresh token
POST http://localhost:3000/auth/refresh-token
content-type: application/json

{
  "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJCdWRpaGFydGEiLCJlbWFpbCI6ImJ1ZGloYXJ0YV8yMUBsaXZlLmNvbSIsImlhdCI6MTcwNTc1OTcyOCwiZXhwIjoxNzA4MzUxNzI4fQ.FL4oGDT0N5SSC4pdBUaDqiDGM76h8K82S6gCyzFGvEk"
}

### Get user
GET http://localhost:3000/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJCdWRpaGFydGEiLCJlbWFpbCI6ImJ1ZGloYXJ0YV8yMUBsaXZlLmNvbSIsImlhdCI6MTcwNTc1OTkwNCwiZXhwIjoxNzA1NzU5OTY0fQ.Zbg0OtV6mpi9HeubTC6I9ztPtk8RqRuS5_FarOkjcaY

### Sign out
POST http://localhost:3000/auth/sign-out
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJCdWRpaGFydGEiLCJlbWFpbCI6ImJ1ZGloYXJ0YV8yMUBsaXZlLmNvbSIsImlhdCI6MTcwNTc1OTkwNCwiZXhwIjoxNzA1NzU5OTY0fQ.Zbg0OtV6mpi9HeubTC6I9ztPtk8RqRuS5_FarOkjcaY

{
  "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJCdWRpaGFydGEiLCJlbWFpbCI6ImJ1ZGloYXJ0YV8yMUBsaXZlLmNvbSIsImlhdCI6MTcwNTc1OTcyOCwiZXhwIjoxNzA4MzUxNzI4fQ.FL4oGDT0N5SSC4pdBUaDqiDGM76h8K82S6gCyzFGvEk"
}
